#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if ! dpkg -l | grep iputils-ping > /dev/null; then
    echo "**** Adding packages to package install list ****"
    echo "\
        iputils-ping\
        dnsutils" >> /mod-repo-packages-to-install.list
else
    echo "**** packages already installed ****"
fi
